# Generated by Django 4.2.2 on 2023-07-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanbanboard',
            name='group_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
