# Generated by Django 4.2.2 on 2023-07-21 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_board', '0002_alter_kanbanboard_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='performer',
            new_name='performers',
        ),
    ]
