# Generated by Django 4.2.2 on 2023-07-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_board', '0003_rename_performer_task_performers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanbanboard',
            name='group_id',
        ),
        migrations.AddField(
            model_name='kanbanboard',
            name='title',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='kanbanboard',
            name='uuid',
            field=models.UUIDField(default=None, null=True, unique=True),
        ),
    ]
