# Generated by Django 4.2.2 on 2023-10-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_board', '0004_remove_kanbanboard_group_id_kanbanboard_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='hidden'),
        ),
    ]
