variables:
  GIT_CLONE_PATH: $CI_BUILDS_DIR/backend

stages:
  - build
  - deploy

build:
  stage: build
  only:
    - backend
  tags:
    - shildichat_backend_runner
  script:
    - docker-compose -p shildichat_backend build

deploy:
  stage: deploy
  only:
    - backend
  tags:
    - shildichat_backend_runner
  script:
    - docker-compose -p shildichat_backend up -d