# Configuration file for Synapse.
#
# This is a YAML file: see [1] for a quick introduction. Note in particular
# that *indentation is important*: all the elements of a list or dictionary
# should have the same indentation.
#
# [1] https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html
#
# For more information on how to configure Synapse, including a complete accounting of
# each option, go to docs/usage/configuration/config_documentation.md or
# https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html
server_name: "localhost"
pid_file: /data/homeserver.pid
listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    resources:
      - names: [client, federation]
        compress: false
database:
  name: psycopg2
  args:
    user: synapse
    password: synapse
    database: synapse
    host: db
    cp_min: 5
    cp_max: 10

log_config: "/data/localhost.log.config"
media_store_path: /data/media_store
registration_shared_secret: "s9hhZgf@7DUBm@86sgzfvv8QKme*jxgr^HN9;0vJVK=0DX:Gpt"
report_stats: true
macaroon_secret_key: "JQUc.z1Rf9Cj+WrkyVpRwFmVVbJv#S39r;HOQSI0Q-~=OaM~aS"
form_secret: "F86KB*Jw-O^H7oq~lqoRqH;HYZQJ8*xuz8Z__JRho58ir9+CC#"
signing_key_path: "/data/localhost.signing.key"
trusted_key_servers:
  - server_name: "matrix.org"


# vim:ft=yaml